name: Build and Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチへのpushで実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # MkDocsをビルド
      - name: Build MkDocs site
        run: mkdocs build

      # ビルド結果をアーティファクトとしてアップロード
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site  # MkDocsのビルドディレクトリ

  deploy:
    runs-on: ubuntu-latest
    needs: build  # ビルドジョブが完了後に実行
    permissions:
      pages: write  # GitHub Pagesへの書き込み権限
      id-token: write  # OIDCトークンの生成

    steps:
      # アーティファクトをデプロイ用にダウンロード
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1